services:
  - type: web
    name: pkmergo
    plan: starter
    env: python
    region: singapore # region should be same as your database region.
    buildCommand: "./build.sh"
    startCommand: "gunicorn run:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
